// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function DeleteWallpaper(arg1:string):Promise<void>;

export function DownloadAndSetWallpaper():Promise<main.WallpaperInfo>;

export function GetSettings():Promise<main.AppSettings>;

export function GetWallpaperAsBase64(arg1:string):Promise<string>;

export function GetWallpaperDirectory():Promise<string>;

export function GetWallpapers():Promise<Array<main.WallpaperInfo>>;

export function OpenWallpaperDirectory():Promise<void>;

export function QuitApp():Promise<void>;

export function SetWallpaper(arg1:string):Promise<void>;

export function ShowWindow():Promise<void>;

export function UpdateSettings(arg1:main.AppSettings):Promise<void>;
