// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DeleteWallpaper(arg1) {
  return window['go']['main']['App']['DeleteWallpaper'](arg1);
}

export function DownloadAndSetWallpaper() {
  return window['go']['main']['App']['DownloadAndSetWallpaper']();
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function GetWallpaperAsBase64(arg1) {
  return window['go']['main']['App']['GetWallpaperAsBase64'](arg1);
}

export function GetWallpaperDirectory() {
  return window['go']['main']['App']['GetWallpaperDirectory']();
}

export function GetWallpapers() {
  return window['go']['main']['App']['GetWallpapers']();
}

export function OpenWallpaperDirectory() {
  return window['go']['main']['App']['OpenWallpaperDirectory']();
}

export function QuitApp() {
  return window['go']['main']['App']['QuitApp']();
}

export function SetWallpaper(arg1) {
  return window['go']['main']['App']['SetWallpaper'](arg1);
}

export function ShowWindow() {
  return window['go']['main']['App']['ShowWindow']();
}

export function UpdateSettings(arg1) {
  return window['go']['main']['App']['UpdateSettings'](arg1);
}
